apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gokapi
  namespace: argocd
spec:
  destination:
    namespace: gokapi
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/andex-tokyo/andex-filetransfer.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
