apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andex-lobechat
  namespace: argocd
spec:
  destination:
    namespace: lobechat
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/andex-tokyo/andex-webui.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
