apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.8.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        crds:
          enabled: true
        
        prometheus:
          prometheusSpec:
            retention: 30d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            resources:
              requests:
                memory: 400Mi
                cpu: 100m
          service:
            type: NodePort
            nodePort: 30090

        grafana:
          adminPassword: admin
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
            datasources:
              enabled: true
          service:
            type: NodePort
            nodePort: 30080

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
            resources:
              requests:
                memory: 100Mi
                cpu: 50m

        prometheus-node-exporter:
          resources:
            requests:
              memory: 30Mi
              cpu: 10m
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true