apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/andex-tokyo/andex-kube-prometheus.git
    targetRevision: HEAD
    kustomize:
      buildOptions: --enable-helm
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true