apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://langfuse.github.io/langfuse-k8s
    targetRevision: 0.10.0
    chart: langfuse
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30080
  destination:
    server: https://kubernetes.default.svc
    namespace: langfuse

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
