apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuclio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nuclio.github.io/nuclio/charts/
    chart: nuclio
    targetRevision: 0.20.6
    helm:
      releaseName: nuclio
      values: |
        dashboard:
          enabled: true
          nodePort: 31112
        controller:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nuclio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
