apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andex-tokyo/andex-obsidian-sync.git
    path: kubernetes
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
