apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  sources:
    - chart: signoz
      targetRevision: 0.70.0
      repoURL: https://charts.signoz.io
      helm:
        releaseName: andex-signoz
        values: |
          frontend:
            service:
              type: NodePort
          otelCollector:
            config:
              receivers:
                prometheus:
                  config:
                    scrape_configs:
                      - job_name: 'argocd-metrics'
                        scrape_interval: 30s
                        kubernetes_sd_configs:
                          - role: endpoints
                            namespaces:
                              names: ['argocd']
                        relabel_configs:
                          - source_labels: [__meta_kubernetes_service_name]
                            action: keep
                            regex: argocd-metrics
                          - source_labels: [__meta_kubernetes_endpoint_port_name]
                            action: keep
                            regex: metrics

                      - job_name: 'argocd-server-metrics'
                        scrape_interval: 30s
                        kubernetes_sd_configs:
                          - role: endpoints
                            namespaces:
                              names: ['argocd']
                        relabel_configs:
                          - source_labels: [__meta_kubernetes_service_name]
                            action: keep
                            regex: argocd-server-metrics
                          - source_labels: [__meta_kubernetes_endpoint_port_name]
                            action: keep
                            regex: metrics

                      - job_name: 'argocd-repo-server'
                        scrape_interval: 30s
                        kubernetes_sd_configs:
                          - role: endpoints
                            namespaces:
                              names: ['argocd']
                        relabel_configs:
                          - source_labels: [__meta_kubernetes_service_name]
                            action: keep
                            regex: argocd-repo-server
                        metrics_path: /metrics

                      - job_name: 'argocd-application-controller'
                        scrape_interval: 30s
                        kubernetes_sd_configs:
                          - role: endpoints
                            namespaces:
                              names: ['argocd']
                        relabel_configs:
                          - source_labels: [__meta_kubernetes_service_name]
                            action: keep
                            regex: argocd-applicationset-controller
                        metrics_path: /metrics
          frontend:
            service:
              type: NodePort
          otelCollector:
            config:
              receivers:
                prometheus:
                  config:
                    global:
                      scrape_interval: 60s
                    scrape_configs:
                      - job_name: 'argocd'
                        kubernetes_sd_configs:
                          - role: endpoints
                            namespaces:
                              names: ['argocd']
                        relabel_configs:
                          - source_labels: [__meta_kubernetes_service_name]
                            action: keep
                            regex: (argocd-metrics|argocd-server|argocd-repo-server)
                          - source_labels: [__meta_kubernetes_endpoint_port_name]
                            action: keep
                            regex: metrics
    - chart: k8s-infra
      targetRevision: 0.12.1
      repoURL: https://charts.signoz.io
      helm:
        releaseName: andex-k8s-infra
        values: |
          otelCollectorEndpoint: http://andex-signoz-otel-collector.signoz.svc.cluster.local:4317
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
