apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  source:
    chart: signoz
    repoURL: https://charts.signoz.io
    targetRevision: 0.70.0
    helm:
      releaseName: andex-signoz
      values: |
        frontend:
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
