apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  project: default
  sources:
    - chart: signoz
      repoURL: https://charts.signoz.io
      targetRevision: 0.70.0
      helm:
        releaseName: andex-signoz
        values: |
          frontend:
            service:
              type: NodePort
    - chart: k8s-infra
      repoURL: https://charts.signoz.io
      targetRevision: 0.12.1
      helm:
        releaseName: andex-k8s-infra
        values: |
          otelCollectorEndpoint: http://andex-signoz-otel-collector.signoz.svc.cluster.local:4317
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: signoz
spec:
  exporter:
    endpoint: http://andex-signoz-otel-collector.signoz.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"  # サンプリングレート（25%）
